randomise();
depth = -100;
activado = 0;
gamepad_connected = 0;
show_confirmation = 0;
show_steam_message = 0;
show_invalid_message = 0;
steam_message = 0;
valid = 0;
level_name = "Untitled";
flip_surf = surface_create(640, 576);
surface_set_target(flip_surf);
draw_clear_alpha(c_black, 0);
surface_reset_target();
shrink_surf = surface_create(640, 576);
surface_set_target(shrink_surf);
draw_clear_alpha(c_black, 0);
surface_reset_target();
screen_surf = surface_create(640, 576);
surface_set_target(screen_surf);
draw_clear_alpha(c_black, 0);
surface_reset_target();
circx = 80;
circy = 72;
circdir = irandom_range(0, 3);
global.show_error_message = 0;
global.error_message = "";
global.show_notification_message = 0;
global.notification_message = "";
global.gamepad = -1;
global.game_restarting = 0;
global.ready_to_send_achievements = 0;
chaos_mode_init = 0;
super_chaos_mode_init = 0;
mega_chaos_mode_init = 0;
payload = 0;
next_payload = -1;
show_snapshot = 0;
take_snapshot = 0;
screen_burn = 0;
shrinking = 0;
shrink_offset = 0;
dizzy_mode = 0;
spr_screen = -1;
topleft_x = 10;
btmleft_x = -10;
mode = 0;
you_are_an_idiot = 0;
screen_x = [];
screen_y = [];
screen_dir = [];
speed_ramping = 0;
speed_mode = 0;
frames = 60;
rewind = 0;
lily_x = [];
lily_y = [];
lily_xscale = [];
lily_action = [];
track_pos = 0;
frozen_trick = 0;
touch_fuzzy_mode = 0;
fuzzy = [];
tick = 0;
start_putting_random_chars_on_screen = 0;
time_between_characters = 10;
show_random_chars = 0;
characters_text = [];
characters_x = [];
characters_y = [];
vhold = 0;
vhold_screen1y = 0;
vhold_screen2y = -144;
vhold_speed = 1;
vhold_mode = 0;
all_coins = 0;
all_clouds = 0;
meteors = 0;
time_between_meteors = 30;
invisible_screen = 0;
