draw_set_colour(c_black);
draw_set_alpha(0.5);
draw_rectangle(0, 0, 160, 144, false);
draw_set_font(global.font);
draw_set_alpha(1);
draw_set_colour(c_white);
draw_set_halign(fa_left);
draw_set_valign(fa_top);
draw_text_ext(0, y, "Hello there, and welcome to our game. Before we continue, you can hold SPACEBAR or any face button on your controller to speed this text up. Press any other key or " + input_verb_get_icon("pause") + " to leave.\n\n--------------------\n\nLet me be straight; thank you so much for downloading this game. I'm Travis, aka Blu, the lead developer of this game and the sole member of Tailfeather Studios. I'm a 22-year-old aspiring game developer based in Michigan, USA. I'm also autistic, so forgive me if I struggle with communication...\n\nI've been developing games since 2009, starting with Scratch but eventually moving to more contemporary programming languages by 2015. Many of my early projects are no longer available due to time or at the request of the IP holder.\n\nBack in 2017 some friends and I had a team set up to make games. Under the name \"Starblaze Studios,\" we'd try to make games using RPG Maker. The team has disbanded since, but one of its members would go on to create vivid/stasis, a rhythm game.\n\nAs for me... I now collect old phones and help preserve their firmwares, including built-in ringtones and wallpapers. You may know me under the name JSR Phones.\n\nAnyway, that's enough about me. That went on for pretty long... Let me introduce you to the rest of my team.\n\n--------------------\n\nHey all, my name is Zach Rouhana and I'm a musician/composer from Upstate NY. I've been playing music seriously for about 10 years and this project was one of my first I composed for. Each sound you hear in the game is taken from the waveform from an actual gameboy and each track is limited to only 4 voices at one time. Hope y'all enjoy the game!\n\n--------------------\n\nHowdy! I'm Paul, a.k.a PureKnix. I put the things in the places for Onward & Upward. Hopefully the right places.  This was my second game jam, and first on a team!\n\nI have immersed myself in amateur level design the past few years and am passionate about games that feature user generated content (UGC).  I hope the level kit tools in O&U inspire you to create something that plays to your heart (or enrages a streamer)!\n\n--------------------\n\nI'd also like to say thanks to my playtesters:\n\n- mothbeanie\n- June Charlotte Whales\n- Strikerwott12\n- Dav999\n- duckbagtm\n...and two anonymous playtesters.\n\n--------------------\n\nAnd that wraps things up for the about us section. Thank you so much for downloading this game, and I hope you get as much enjoyment out of it as possible! Press any key or " + input_verb_get_icon("pause") + " to leave, and thanks again to the rest of my game jam team for their excellent work on this game. I couldn't have done it without you!", 9, 160);
