draw_set_colour(#00B6FF);
draw_rectangle(0, 0, 256, 192, false);
draw_sprite_ext(spr_logo, 0, x + (sin(tick - 7) * multiplier), y + 6, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 1, x + (sin(tick - 6) * multiplier), y + 5, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 2, x + (sin(tick - 5) * multiplier), y + 4, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 3, x + (sin(tick - 4) * multiplier), y + 3, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 4, x + (sin(tick - 3) * multiplier), y + 2, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 5, x + (sin(tick - 2) * multiplier), y + 1, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 6, x + (sin(tick - 1) * multiplier), y, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 7, x + (sin(tick) * multiplier), y - 1, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 8, x + (sin(tick + 1) * multiplier), y - 2, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 9, x + (sin(tick + 2) * multiplier), y - 3, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 10, x + (sin(tick + 3) * multiplier), y - 4, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 11, x + (sin(tick + 4) * multiplier), y - 5, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 12, x + (sin(tick + 5) * multiplier), y - 6, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 13, x + (sin(tick + 6) * multiplier), y - 7, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 14, x + (sin(tick + 7) * multiplier), y - 8, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 15, x + (sin(tick + 8) * multiplier), y - 9, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 16, x + (sin(tick + 9) * multiplier), y - 10, 1, 1, 0, c_white, 1);
draw_sprite_ext(spr_logo, 17, x + (sin(tick + 10) * multiplier), y - 11, 1, 1, 0, c_white, 1);
